### ISSUE TITLE
Meta issue: issues involving potential runtime errors

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/core#377]
These are `core` issues that are currently known to cause potential runtime exceptions:

- [ ] #201 Weird tuple error
- [ ] #177 Broken eq on some unicode strings 
- [ ] #183 `toString Json.Encode.null`
- [ ] #294 `Json.Encode.null == Json.Encode.object []` (and other comparisons of null with non-null)

**Comment by mgold** [comment]
Old issue: elm-lang/elm-compiler#913.

Runtime errors can be broken down into those that can occur at any time, and those that must occur immediately. An orthogonal breakdown is difficulty of fixing: mere bugs, vs. things that will require more thought. Some of the ones in the second one aren't bugs but language choices, but it's nice to have an exhaustive list. I mark these with a bullet rather than a checkbox.

I'll try to keep this up to date.

## Bugs - Any Time
* Everything listed by @rtfeldman 

## Harder - Any Time
* [ ] #378 - ill-formed regex (harder because it means changing the API)
* [ ] elm-lang/elm-compiler#873 - recursively defined values
* `Debug.crash`
* Infinite recursion/stack overflow
* Function and signal equality
* Incomplete matching, e.g. `(\(Just x) -> x) Nothing`


## Bugs - Immediate
_None Known?_

## Harder - Immediate
* Improperly initialized ports
* `Signal.mergeMany []`

**Comment by evancz** [comment]
@mgold, can you edit your comment to only focus on "core" issues? I don't want a mishmash of cross-repo things to track. I also want to focus on concrete API things that we can resolve, for me this is not supposed to be a comprehensive list of all things that can cause a runtime error. "Stack overflows are possible" is more of a language and CS thing than something for this issue.

@rtfeldman, maybe bring in the parts of the comment that are relevant for this issue and then I can delete the comments to keep things clearer. Generally speaking "meta issues" are not for comments and discussion. They are an strategy for describing and organizing specific topics in a way that normal issues inherently do not do. If you want to add to them, open a separate issue and it'll get moved if necessary.

**Comment by rtfeldman** [comment]
@evancz Gotcha. I have merged @mgold's comment into the original description.

**Comment by jvoigtlaender** [comment]
What about https://github.com/elm-lang/core/issues/349? Does it belong in the collection of errors here?

**Comment by mgold** [comment]
I would say it does.

**Comment by rtfeldman** [comment]
Makes sense to me! It is a `core` issue that causes a runtime exception, after all.

**Comment by mgold** [comment]
Is it worth distinguishing between fixes that require API changes (rexeges, mergeMany) and those that are just bugs (like array slice)?

**Comment by rtfeldman** [comment]
The original issue included e.g. #201, so I would say they're fair game.

**Comment by eeue56** [comment]
Do we have a way of adding RuntimeException tests to the core-test suite? Is there any currently available Elm test-suite that offers that functionality? It would be nice to have something to back up my testing with more than just running things and checking if they error out.

**Comment by eeue56** [comment]
#390 creates a runtime error when dealing with touches if you're embedding Elm rather than using it fullscreen

**Comment by gogocurtis** [comment]
<3

**Comment by gogocurtis** [comment]
❤️ 😍
