### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by lukewestby** [elm-lang/core#816]
There seem to be a few issues popping up around Dates including some duplicates of previously closed issues, so lets track them here

  - [x] #632 - Browser inconsistencies in parsing with `new Date()`
  - [ ] #690 - Sufficiently large numbers crash `Date.fromTime`
  - [ ] #755, #739 - Getting timezone offset for Dates
  - [x] #481, #810 - `toString date` results in a string that is not consistently parseable as a Date
  - [ ] #857 - Construct a Date from year, month, day
  - [ ] #855 - `Date.fromString` interacts with browser env
  - [ ] #851 - Date type is not comparable

Some summarizing of things that Dates need to resolve issues:

- Consistent, crash-free parsing of inputs (ISO strings and `Time`s)
- Support for UTC offset
- Consistent, possibly standard-compliant output from `toString`

**Comment by evancz** [comment]
I changed `Date.fromString` to `Date.fromIso8601` which verifies the format and cannot crash.

I also added `Date.toIso8601` which always produces a `String` in the same format.

I believe the issue with browsers adding in time zone information can be resolved if these two functions are moved into `Time` which does not care about time zones. Then perhaps `Date` should move out of core, either to `elm-lang/date` or a community package, until we can do something [like this](https://github.com/evancz/time-zone-database-proposal).
